### PR TITLE
Update fonts

### LINKED ISSUE #47: Missing glyphs in Fluent icons
## Current behavior

Missing the following:

- E708 - Quiet hours
- E62E - Pause solid (seems the same as F8AE)
- F2B7 - LocaleLanguage
- F71C - StartPresenting
- F540 - Safe
- EC19 - PLAP (This one shows the wrong icon, it should be PLAP)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

### PR DESCRIPTION
**Pull request by d2dyno1**
GitHub Issue (If applicable): #

## PR Type

Update some fonts mentioned in #47
Closes #47

## What is the current behavior?

image

## What is the new behavior?

image

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by d2dyno1** [comment]
I've hand-exported and imported icons from Segoe Fluent Icons directly into Uno fluent icons

**Comment by d2dyno1** [comment]
Tagging members for visibility: @MartinZikmund @jeromelaban

**Comment by MartinZikmund** [comment]
@d2dyno1 thanks for the PR, but currently we are using icomoon to generate the font - @NVLudwig has those source files, so he would be able to update the font and generate the proper files, if you upload the SVGs you have used here

**Comment by agneszitte** [comment]
@MartinZikmund, @NVLudwig as https://github.com/unoplatform/uno.fonts/pull/50 is now merged, what is the status for this current PR please?

**Comment by d2dyno1** [comment]
Thanks for the update! I think this can be closed now...

**Pull request closed without merging**
